server:
  servlet:
    context-path: /crud
  tomcat:
    uri-encoding: utf-8
  error:
    include-exception: true
    include-message: always
  port: 8888


spring:
  messages:
    basename: i18n.login
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  mvc:
    format:
      date: yyyy-MM-dd
    hiddenmethod:
      filter:
        enabled: true